#!/usr/bin/env python3

import json
from pathlib import Path

BATCH_DIR = Path('/home/olibuijr/Projects/olfong_stack/backend/translation-batches')

# COMPREHENSIVE TRANSLATION DICTIONARY WITH 1000+ ENTRIES
COMPREHENSIVE_TRANSLATIONS = {
    # CSS and Structure
    '.link-dropdown-container': 'Tengill-fellivalmöguleikar',
    '.relative': 'Afstætt',
    '24.00': '24,00',
    '25.00': '25,00',
    '27.50': '27,50',

    # Addresses
    'addresses.add': 'Bæta við heimilisfangi',
    'addresses.city': 'Borg',
    'addresses.country': 'Land',
    'addresses.delete': 'Eyða heimilisfangi',
    'addresses.edit': 'Breyta heimilisfangi',
    'addresses.postalCode': 'Póstnúmer',
    'addresses.street': 'Gata',

    # Admin Access
    'admin.accessDenied': 'Aðgangur ekki leyfður',
    'admin.accessDeniedMessage': 'Þú hefur ekki réttindi til að fá aðgang að þessum gögnum.',

    # Admin Banners
    'admin.banners.activate': 'Virkja borða',
    'admin.banners.addBanner': 'Bæta við borða',
    'admin.banners.addFirstBanner': 'Bæta við fyrsta borða',
    'admin.banners.addToFeatured': 'Bæta við vörunum sem birtar eru',
    'admin.banners.altPlaceholder': 'Skrifaðu lýsingu fyrir aðgengileika',
    'admin.banners.altText': 'Annar texti myndar',
    'admin.banners.category': 'Flokkur',
    'admin.banners.confirmDelete': 'Staðfestu eyðingu',
    'admin.banners.deactivate': 'Gera óvirka',
    'admin.banners.descriptionEn': 'Lýsing (Enska)',
    'admin.banners.descriptionIs': 'Lýsing (Íslenska)',
    'admin.banners.descriptionPlaceholder': 'Sláðu inn lýsingu á ensku',
    'admin.banners.descriptionPlaceholderIs': 'Sláðu inn lýsingu á íslensku',
    'admin.banners.editBanner': 'Breyta borða',
    'admin.banners.featured': 'Vöruð',
    'admin.banners.featuredBanner': 'Vöruð borði',
    'admin.banners.featuredBannerHelp': 'Þessi borði birtist á forsíðu',
    'admin.banners.featuredOrder': 'Röð vöruðra borða',
    'admin.banners.imageHelpText': 'Hlaððu upp myndarskrá eða settu inn vefslóð',
    'admin.banners.imageUrl': 'Vefslóð myndar',
    'admin.banners.link': 'Tengill',
    'admin.banners.manageImages': 'Stjórna myndum',
    'admin.banners.noBanners': 'Engir borðar',
    'admin.banners.noBannersDescription': 'Byrjaðu á því að bæta við fyrri borða',
    'admin.banners.noDescription': 'Engin lýsing',
    'admin.banners.position': 'Staðsetning',
    'admin.banners.product': 'Vara',
    'admin.banners.removeFromFeatured': 'Fjarlægja úr vöruðum vörum',
    'admin.banners.selectLink': 'Veldu tengil',
    'admin.banners.selectPosition': 'Veldu staðsetningu',
    'admin.banners.sortOrder': 'Röðunarröð',
    'admin.banners.subcategory': 'Undirflokkur',
    'admin.banners.subtitle': 'Undirrubrik',
    'admin.banners.title': 'Titill',
    'admin.banners.titleEn': 'Titill (Enska)',
    'admin.banners.titleIs': 'Titill (Íslenska)',
    'admin.banners.titlePlaceholder': 'Sláðu inn titil á ensku',
    'admin.banners.titlePlaceholderIs': 'Sláðu inn titil á íslensku',
    'admin.banners.untitled': 'Ótitlað',

    # Admin Analytics
    'adminAnalytics.analyticsDashboard': 'Greiningartöflur',
    'adminAnalytics.businessInsights': 'Innsýn í viðskipti',
    'adminAnalytics.cancelled': 'Afturkölluð',
    'adminAnalytics.category': 'Flokkur',
    'adminAnalytics.delivered': 'Afhent',
    'adminAnalytics.export': 'Flytja út',
    'adminAnalytics.growth': 'Vöxtur',
    'adminAnalytics.last30Days': 'Síðustu 30 dagar',
    'adminAnalytics.last7Days': 'Síðustu 7 dagar',
    'adminAnalytics.last90Days': 'Síðustu 90 dagar',
    'adminAnalytics.lastYear': 'Síðasta ár',
    'adminAnalytics.loading': 'Hleður...',
    'adminAnalytics.netRevenue': 'Hrein tekjur',
    'adminAnalytics.noData': 'Engin gögn',
    'adminAnalytics.noProducts': 'Engar vörur',
    'adminAnalytics.noRevenueData': 'Engin tekjugögn',
    'adminAnalytics.ofRevenue': 'af tekjum',
    'adminAnalytics.ofVat': 'af VSK',
    'adminAnalytics.orders': 'Pantanir',
    'adminAnalytics.orderStatusDistribution': 'Dreifing pöntunartölfræði',
    'adminAnalytics.pending': 'Bið',
    'adminAnalytics.processing': 'Vinnsla',
    'adminAnalytics.product': 'Vara',
    'adminAnalytics.revenue': 'Tekjur',
    'adminAnalytics.revenueBeforeVat': 'Tekjur fyrir VSK',
    'adminAnalytics.revenueTrend': 'Þróun tekna',
    'adminAnalytics.sales': 'Sala',
    'adminAnalytics.shipped': 'Sendað',
    'adminAnalytics.topPerformer': 'Besti framkvæmandi',
    'adminAnalytics.topPerformingProducts': 'Bestu framleiðandi vörur',
    'adminAnalytics.totalCustomers': 'Heildarfjöldi viðskiptavina',
    'adminAnalytics.totalOrders': 'Heildarfjöldi pantana',
    'adminAnalytics.totalProducts': 'Heildarvigur vara',
    'adminAnalytics.totalRevenue': 'Heildartek',
    'adminAnalytics.totalVat': 'Heildar VSK',
    'adminAnalytics.unknownCategory': 'Óþekkt flokkur',
    'adminAnalytics.unknownProduct': 'Óþekkt vara',
    'adminAnalytics.vsPreviousPeriod': 'samanborið við fyrri tímabil',

    # Admin Categories
    'adminCategories.active': 'Virk',
    'adminCategories.basicInfo': 'Grunnupplýsingar',
    'adminCategories.cannotDeleteWithProducts': 'Ekki er hægt að eyða flokki sem inniheldur vörur',
    'adminCategories.categoryImageFromProduct': 'Myndaveita flokks',
    'adminCategories.changeImage': 'Breyta mynd',
    'adminCategories.confirmDelete': 'Staðfestu eyðingu',
    'adminCategories.createFirstCategory': 'Búðu til fyrsta flokk',
    'adminCategories.descEn': 'Lýsing (Enska)',
    'adminCategories.descIs': 'Lýsing (Íslenska)',
    'adminCategories.description': 'Lýsing',
    'adminCategories.discountEndDate': 'Lok afsláttarlosunar',
    'adminCategories.discountHelp': 'Hjálp fyrir afslátt',
    'adminCategories.discountPercentage': 'Afsláttarprósenta',
    'adminCategories.discountReasonEn': 'Ástæða afsláttar (Enska)',
    'adminCategories.discountReasonIs': 'Ástæða afsláttar (Íslenska)',
    'adminCategories.discounts': 'Afslættir',
    'adminCategories.discountStartDate': 'Upphaf afsláttarlosunar',
    'adminCategories.editCategory': 'Breyta flokki',
    'adminCategories.enableCategoryDiscount': 'Virkja flokksafslátt',
    'adminCategories.enableDiscountMessage': 'Virkjaðu afslætti',
    'adminCategories.icon': 'Tákn',
    'adminCategories.iconHelp': 'Aðstoð takna',
    'adminCategories.images': 'Myndir',
    'adminCategories.inactive': 'Óvirk',
    'adminCategories.manageCategories': 'Stjórna flokkum',
    'adminCategories.metaDescEn': 'Meta lýsing (Enska)',
    'adminCategories.metaDescIs': 'Meta lýsing (Íslenska)',
    'adminCategories.metaTitleEn': 'Meta titill (Enska)',
    'adminCategories.metaTitleIs': 'Meta titill (Íslenska)',
    'adminCategories.name': 'Nafn',
    'adminCategories.nameEn': 'Nafn (Enska)',
    'adminCategories.nameIs': 'Nafn (Íslenska)',
    'adminCategories.nameRequired': 'Nafn er krafist',
    'adminCategories.newCategory': 'Nýr flokkur',
    'adminCategories.noCategories': 'Engir flokkar',
    'adminCategories.noDescription': 'Engin lýsing',
    'adminCategories.productCount': 'Vörutalning',
    'adminCategories.rate': 'Hlutfall',
    'adminCategories.removeImage': 'Fjarlægja mynd',
    'adminCategories.selectedVatProfile': 'Valinn VSK prófíl',
    'adminCategories.selectFromMedia': 'Veldu úr miðlum',
    'adminCategories.selectVatProfile': 'Veldu VSK prófíl',
    'adminCategories.seo': 'SEO',
    'adminCategories.seoHelp': 'SEO hjálp',
    'adminCategories.slug': 'Slög',
    'adminCategories.slugHelp': 'Hjálp fyrir slög',
    'adminCategories.sortOrder': 'Röðunarröð',
    'adminCategories.subcategories': 'Undirflokkar',
    'adminCategories.title': 'Titill',
    'adminCategories.vat': 'VSK',
    'adminCategories.vatHelp': 'VSK hjálp',
    'adminCategories.vatProfile': 'VSK prófíl',
    'adminCategories.vatProfileHelp': 'VSK prófíl hjálp',

    # Admin Chat
    'adminChat.accessDenied': 'Aðgangur ekki leyfður',
    'adminChat.accessDeniedMessage': 'Þú hefur ekki réttindi til að fá aðgang að þessum gögnum.',
    'adminChat.active': 'Virk',
    'adminChat.allStatuses': 'Allar stöður',
    'adminChat.archived': 'Safnað',
    'adminChat.customerTyping': 'Viðskiptavinur er að skrifa',
    'adminChat.noConversations': 'Engin samtöl',
    'adminChat.noMessages': 'Engin skilaboð',

    # Admin Customers
    'adminCustomers.address': 'Heimilisfang',
    'adminCustomers.allCustomers': 'Allir viðskiptavinir',
    'adminCustomers.createdDate': 'Búið til dagsetning',
    'adminCustomers.email': 'Tölvupóstur',
    'adminCustomers.firstName': 'Fornafn',
    'adminCustomers.lastOrder': 'Síðasta pöntun',
    'adminCustomers.lastName': 'Eftirnafn',
    'adminCustomers.noCustomers': 'Engir viðskiptavinir',
    'adminCustomers.phone': 'Símanúmer',
    'adminCustomers.totalOrders': 'Heildarfjöldi pantana',
    'adminCustomers.totalSpent': 'Heildarútgjöld',
    'adminCustomers.viewDetails': 'Skoðaðu smáatriði',

    # Admin Dashboard
    'adminDashboard.analytics': 'Greiningar',
    'adminDashboard.latestOrders': 'Nýjustu pantanir',
    'adminDashboard.overview': 'Yfirlit',
    'adminDashboard.quickStats': 'Hraðar tölfræðir',
    'adminDashboard.recentActivity': 'Nýleg virkni',
    'adminDashboard.revenue': 'Tekjur',
    'adminDashboard.topProducts': 'Bestu vörur',
    'adminDashboard.welcome': 'Velkomin/n',

    # Admin Labels
    'adminLabels.add': 'Bæta við',
    'adminLabels.cancel': 'Hætta við',
    'adminLabels.delete': 'Eyða',
    'adminLabels.edit': 'Breyta',
    'adminLabels.save': 'Vista',
    'adminLabels.saving': 'Vistar...',
    'adminLabels.view': 'Skoðaðu',

    # Admin Media
    'adminMedia.addMedia': 'Bæta við miðlum',
    'adminMedia.altText': 'Annar texti',
    'adminMedia.deleteConfirm': 'Ertu viss um að þú viljir eyða þessu miðli?',
    'adminMedia.description': 'Lýsing',
    'adminMedia.fileName': 'Skráarheiti',
    'adminMedia.imageSource': 'Myndaveita',
    'adminMedia.manageMedia': 'Stjórna miðlum',
    'adminMedia.noMedia': 'Engin miðil',
    'adminMedia.title': 'Titill',
    'adminMedia.uploadDate': 'Hlaðar dagsetning',
    'adminMedia.uploadNew': 'Hlaða upp nýjum miðlum',
    'adminMedia.uploadProgress': 'Hlaðan framvinda',
    'adminMedia.uploadedBy': 'Hlaðið af',

    # Admin Menu
    'adminMenu.analytics': 'Greiningar',
    'adminMenu.banners': 'Borðar',
    'adminMenu.categories': 'Flokkar',
    'adminMenu.chat': 'Spjall',
    'adminMenu.customers': 'Viðskiptavinir',
    'adminMenu.dashboard': 'Stjórnandi borð',
    'adminMenu.deliveries': 'Sendingar',
    'adminMenu.discounts': 'Afslættir',
    'adminMenu.general': 'Almennt',
    'adminMenu.media': 'Miðlar',
    'adminMenu.notifications': 'Tilkynningar',
    'adminMenu.orders': 'Pantanir',
    'adminMenu.pos': 'POS',
    'adminMenu.products': 'Vörur',
    'adminMenu.reports': 'Skýrslur',
    'adminMenu.settings': 'Stillingar',
    'adminMenu.translations': 'Þýðingar',
    'adminMenu.vatProfiles': 'VSK prófílar',

    # Admin Navigation
    'adminNavigation.dashboard': 'Stjórnandi borð',
    'adminNavigation.exportData': 'Flytja út gögn',
    'adminNavigation.help': 'Hjálp',
    'adminNavigation.importData': 'Flytja inn gögn',
    'adminNavigation.language': 'Tungumál',
    'adminNavigation.logout': 'Útskrá',
    'adminNavigation.myProfile': 'Minn prófíl',
    'adminNavigation.settings': 'Stillingar',

    # Admin Notifications
    'adminNotifications.create': 'Búðu til tilkynningu',
    'adminNotifications.deleteConfirm': 'Ertu viss um að þú viljir eyða þessari tilkynningu?',
    'adminNotifications.description': 'Lýsing',
    'adminNotifications.edit': 'Breyta tilkynningu',
    'adminNotifications.icon': 'Tákn',
    'adminNotifications.message': 'Skilaboð',
    'adminNotifications.noNotifications': 'Engar tilkynningar',
    'adminNotifications.publish': 'Gefa út',
    'adminNotifications.schedule': 'Tímasetning',
    'adminNotifications.title': 'Titill',
    'adminNotifications.type': 'Tegund',
    'adminNotifications.viewAll': 'Skoðaðu allt',

    # Admin Page
    'adminPage.activeUsers': 'Virkir notendur',
    'adminPage.conversionRate': 'Viðskipta hlutfall',
    'adminPage.dashboard': 'Stjórnandi borð',
    'adminPage.goodMorning': 'Halló og góðan daginn',
    'adminPage.lastUpdated': 'Síðast uppfært',
    'adminPage.pageViews': 'Síðuskoðanir',
    'adminPage.revenue': 'Tekjur',
    'adminPage.salesGrowth': 'Söluvöxtur',
    'adminPage.systemStatus': 'Kerfi staða',
    'adminPage.topPages': 'Bestu síður',
    'adminPage.topSellingProducts': 'Mest seldu vörur',
    'adminPage.totalOrders': 'Heildarfjöldi pantana',
    'adminPage.userActivity': 'Notanda virkni',

    # Admin Placeholders
    'adminPlaceholders.description': 'Sláðu inn lýsingu',
    'adminPlaceholders.email': 'Sláðu inn tölvupóst',
    'adminPlaceholders.firstName': 'Sláðu inn fornafn',
    'adminPlaceholders.lastName': 'Sláðu inn eftirnafn',
    'adminPlaceholders.phone': 'Sláðu inn símanúmer',
    'adminPlaceholders.searchProducts': 'Leita að vörum',
    'adminPlaceholders.title': 'Sláðu inn titil',

    # Admin Products
    'adminProducts.importFromATVR': 'Flytja inn frá ATVR',

    # Admin Product Modal
    'adminProductModal.unsavedChanges': 'Óvistuðar breytingar',

    # Admin Products Page
    'adminProductsPage.addProduct': 'Bæta við vöru',
    'adminProductsPage.allProducts': 'Allar vörur',
    'adminProductsPage.category': 'Flokkur',
    'adminProductsPage.deleteConfirm': 'Ertu viss um að þú viljir eyða þessari vöru?',
    'adminProductsPage.editProduct': 'Breyta vöru',
    'adminProductsPage.noProducts': 'Engar vörur',
    'adminProductsPage.price': 'Verð',
    'adminProductsPage.productName': 'Vöruheiti',
    'adminProductsPage.quantity': 'Magn',
    'adminProductsPage.sku': 'SKU',
    'adminProductsPage.status': 'Staða',

    # Admin Reports
    'adminReports.createReport': 'Búðu til skýrslu',
    'adminReports.customDateRange': 'Sérsniðin dagsetningarbil',
    'adminReports.customerReport': 'Viðskiptavinaskýrsla',
    'adminReports.dateRange': 'Dagsetningarbil',
    'adminReports.endDate': 'Lokadagsetning',
    'adminReports.export': 'Flytja út',
    'adminReports.exportFormat': 'Útflutningssnið',
    'adminReports.generatingReport': 'Búa til skýrslu',
    'adminReports.inventory': 'Birgðir',
    'adminReports.monthly': 'Mánaðarlega',
    'adminReports.monthly': 'Mánaðarlega',
    'adminReports.products': 'Vörur',
    'adminReports.productsReport': 'Vöruskýrsla',
    'adminReports.refreshData': 'Endurnýja gögn',
    'adminReports.reportType': 'Tegund skýrslu',
    'adminReports.revenue': 'Tekjur',
    'adminReports.revenueByCategory': 'Tekjur eftir flokki',
    'adminReports.salesReport': 'Söluskýrsla',
    'adminReports.startDate': 'Upphafsdagsetning',
    'adminReports.thisPeriod': 'Þetta tímabil',
    'adminReports.timePeriod': 'Tímabil',
    'adminReports.topCustomersByRevenue': 'Efstu viðskiptavinir eftir tekjum',
    'adminReports.topSellingProducts': 'Mest seldu vörur',
    'adminReports.totalCustomers': 'Heildarfjöldi viðskiptavina',
    'adminReports.totalOrders': 'Heildarfjöldi pantana',
    'adminReports.totalProducts': 'Heildarvigur vara',
    'adminReports.totalRevenue': 'Heildartek',
    'adminReports.vsPreviousPeriod': 'samanborið við fyrri tímabil',
    'adminReports.weekly': 'Vikulega',
    'adminReports.yearly': 'Ársleg',

    # Admin Settings - Large Section
    'adminSettings.aboutUs': 'Um okkur',
    'adminSettings.accentColor': 'Áherslulitur',
    'adminSettings.accessDenied': 'Aðgangur ekki leyfður',
    'adminSettings.accessKey': 'Aðgangslykilur',
    'adminSettings.accountEmail': 'Reikningsnetfang',
    'adminSettings.accountPassword': 'Reikningslykilorð',
    'adminSettings.add': 'Bæta við',
    'adminSettings.addFirstIntegration': 'Bæta við fyrstu samþættingu',
    'adminSettings.addFirstPaymentGateway': 'Bæta við fyrstu greiðslumöttul',
    'adminSettings.addFirstShippingOption': 'Bæta við fyrsti sendingarvalkosti',
    'adminSettings.addIntegration': 'Bæta við samþættingu',
    'adminSettings.addPaymentGateway': 'Bæta við greiðslumöttul',
    'adminSettings.addProfile': 'Bæta við prófíl',
    'adminSettings.addressEnglish': 'Heimilisfang (Enska)',
    'adminSettings.addressIcelandic': 'Heimilisfang (Íslenska)',
    'adminSettings.addShippingOption': 'Bæta við sendingarvalkosti',
    'adminSettings.ageRestriction': 'Aldurstakmörkun',
    'adminSettings.ageRestrictionDescription': 'Aldurstakmörkun lýsing',
    'adminSettings.ageRestrictionNotice': 'Aldurstakmörkun tilkynning',
    'adminSettings.ageRestrictions': 'Aldurtakmörkun',
    'adminSettings.alcoholNicotineAgeDescription': 'Aldur fyrir alkóhól og nikotin',
    'adminSettings.alcoholNicotineProducts': 'Alkóhól- og nikótínvörur',
    'adminSettings.apiKey': 'API-lykill',
    'adminSettings.apiKeys': 'API-lyklar',
    'adminSettings.apiKeysConfiguration': 'Stillingar API-lykla',
    'adminSettings.apiKeysDescription': 'Lýsing API-lykla',
    'adminSettings.apiKeysImportantNote1': 'Mikilvæg athugasemd 1',
    'adminSettings.apiKeysImportantNote2': 'Mikilvæg athugasemd 2',
    'adminSettings.apiKeysImportantNote3': 'Mikilvæg athugasemd 3',
    'adminSettings.apiKeysImportantNote4': 'Mikilvæg athugasemd 4',
    'adminSettings.applicationId': 'Kenni forrit',
    'adminSettings.assignCategories': 'Úthluta flokkum',
    'adminSettings.avgHoursPerDay': 'Meðaltal klukkustunda á dag',
    'adminSettings.backupSettings': 'Öryggisafritun stillinga',
    'adminSettings.baseUrl': 'Grunnvefslóð',
    'adminSettings.beCustomer': 'Vertu viðskiptavinur',
    'adminSettings.branding': 'Vörumerki',
    'adminSettings.brandingDescription': 'Lýsing vörumerkis',
    'adminSettings.businessEmail': 'Netfang fyrirtækis',
    'adminSettings.businessHours': 'Opnunartímar',
    'adminSettings.business': 'Viðskipti',
    'adminSettings.businessDescription': 'Lýsing á viðskiptum',
    'adminSettings.businessName': 'Nafn fyrirtækis',
    'adminSettings.businessPhone': 'Símanúmer fyrirtækis',
    'adminSettings.businessType': 'Tegund viðskipta',
    'adminSettings.cancel': 'Hætta við',
    'adminSettings.capturePaymentAutomatically': 'Taktu greiðslu sjálfkrafa',
    'adminSettings.checkConnection': 'Athugaðu tengingu',
    'adminSettings.closeTime': 'Lokunartími',
    'adminSettings.color': 'Litur',
    'adminSettings.colors': 'Litir',
    'adminSettings.configuration': 'Stillingar',
    'adminSettings.configurationDescription': 'Lýsing stillinga',
    'adminSettings.connectivity': 'Tenging',
    'adminSettings.connectivityDescription': 'Lýsing tengingar',
    'adminSettings.contactEmail': 'Hafa samband tölvupóstur',
    'adminSettings.contactPhone': 'Hafðu samband símanúmer',
    'adminSettings.countryName': 'Landsheiti',
    'adminSettings.currencyCode': 'Gjaldmiðilskóði',
    'adminSettings.currencySymbol': 'Gjaldmiðilstákn',
    'adminSettings.customFields': 'Sérstillir reitir',
    'adminSettings.customIntegration': 'Sérstillt samþætting',
    'adminSettings.customer': 'Viðskiptavinur',
    'adminSettings.customerAddress': 'Heimilisfang viðskiptavinar',
    'adminSettings.customerEmail': 'Tölvupóstur viðskiptavinar',
    'adminSettings.customerName': 'Nafn viðskiptavinar',
    'adminSettings.customerPhone': 'Símanúmer viðskiptavinar',
    'adminSettings.dashboard': 'Stjórnandi borð',
    'adminSettings.data': 'Gögn',
    'adminSettings.dataBackup': 'Gögn öryggisafritun',
    'adminSettings.dataBackupDescription': 'Lýsing gagna öryggisafritunar',
    'adminSettings.dataManagement': 'Gagnastjórnun',
    'adminSettings.dataManagementDescription': 'Lýsing gagnastjórnunar',
    'adminSettings.daysOfWeek': 'Dagar vikunnar',
    'adminSettings.defaultCurrency': 'Sjálfgefinn gjaldmiðill',
    'adminSettings.defaultLanguage': 'Sjálfgefið tungumál',
    'adminSettings.defaultPaymentGateway': 'Sjálfgefin greiðslumöttul',
    'adminSettings.defaultShippingMethod': 'Sjálfgefin sendingaraðferð',
    'adminSettings.delete': 'Eyða',
    'adminSettings.deleteAccount': 'Eyða reikningi',
    'adminSettings.deleteAccountConfirmation': 'Ertu viss um að þú viljir eyða þessum reikningi?',
    'adminSettings.deliveryPersonName': 'Nafn sendingaraðila',
    'adminSettings.deliveryPersonPhone': 'Símanúmer sendingaraðila',
    'adminSettings.description': 'Lýsing',
    'adminSettings.descriptionPlaceholder': 'Sláðu inn lýsingu',
    'adminSettings.details': 'Smáatriði',
    'adminSettings.discount': 'Afsláttur',
    'adminSettings.displayCurrencyCode': 'Birta gjaldmiðilskóða',
    'adminSettings.displayCurrencySymbol': 'Birta gjaldmiðilstákn',
    'adminSettings.edit': 'Breyta',
    'adminSettings.editPaymentGateway': 'Breyta greiðslumöttul',
    'adminSettings.editProfile': 'Breyta prófíl',
    'adminSettings.editShippingOption': 'Breyta sendingarvalkosti',
    'adminSettings.email': 'Tölvupóstur',
    'adminSettings.emailHost': 'Tölvupósts hýsill',
    'adminSettings.emailPassword': 'Tölvupóstslykilorð',
    'adminSettings.emailPort': 'Tölvupóstshöfn',
    'adminSettings.emailSettings': 'Stillingar tölvupósts',
    'adminSettings.emailUsername': 'Tölvupóstsnotandanafn',
    'adminSettings.enable': 'Virkja',
    'adminSettings.enableAgeVerification': 'Virkja aldursstaðfestingu',
    'adminSettings.enableEmail': 'Virkja tölvupóst',
    'adminSettings.enablePaymentGateway': 'Virkja greiðslumöttul',
    'adminSettings.enablePromoCodes': 'Virkja kynningarstafi',
    'adminSettings.enableSMS': 'Virkja SMS',
    'adminSettings.endDate': 'Lokadagsetning',
    'adminSettings.environmentalSettings': 'Umhverfissstillingar',
    'adminSettings.errorConnecting': 'Villa við tengingu',
    'adminSettings.errorFetchingSettings': 'Villa við sókn stilligna',
    'adminSettings.errorSavingSettings': 'Villa við að vista stillingar',
    'adminSettings.existingPaymentGateway': 'Fyrirliggjandi greiðslumöttul',
    'adminSettings.expand': 'Stækka',
    'adminSettings.exportData': 'Flytja út gögn',
    'adminSettings.exportSettings': 'Flytja út stillingar',
    'adminSettings.failureMessage': 'Bilun skilaboð',
    'adminSettings.faviconUrl': 'Favicon vefslóð',
    'adminSettings.features': 'Eiginleikar',
    'adminSettings.feedbackEmail': 'Athugasemdir tölvupóstur',
    'adminSettings.feePercentage': 'Gjaldprósenta',
    'adminSettings.feePercentageDescription': 'Gjaldprósenta lýsing',
    'adminSettings.firstName': 'Fornafn',
    'adminSettings.fixedFee': 'Fast gjald',
    'adminSettings.fixedFeeDescription': 'Fast gjald lýsing',
    'adminSettings.flexibleShipping': 'Sveigjanleg sending',
    'adminSettings.flexibleShippingDescription': 'Sveigjanleg sendingarljóskindaslýsing',
    'adminSettings.freeShippingThreshold': 'Frjáls sendingarþröskuldur',
    'adminSettings.fridayHours': 'Föstudags opnunartímar',
    'adminSettings.fullName': 'Fullt nafn',
    'adminSettings.general': 'Almennt',
    'adminSettings.generalDescription': 'Almennt lýsing',
    'adminSettings.generalSettings': 'Almennar stillingar',
    'adminSettings.generalSettingsDescription': 'Almenn lýsing stillinga',
    'adminSettings.getApiKey': 'Farðu með API lykil',
    'adminSettings.getApiKeys': 'Farðu með API lykla',
    'adminSettings.getStarted': 'Byrjaðu',
    'adminSettings.globalShippingCost': 'Alheimur sendingarverð',
    'adminSettings.googleAnalytics': 'Google Analytics',
    'adminSettings.googleAnalyticsDescription': 'Google Analytics lýsing',
    'adminSettings.googleAnalyticsId': 'Google Analytics auðkenni',
    'adminSettings.googleAnalyticsTracking': 'Google Analytics rekningarstöðu',
    'adminSettings.guestCheckoutAllowed': 'Gestakassi leyfð',
    'adminSettings.handleRefunds': 'Taktu ávöxtun',
    'adminSettings.hashKey': 'Hash-lykill',
    'adminSettings.hidePrice': 'Fela verð',
    'adminSettings.hostUrl': 'Hýsill vefslóð',
    'adminSettings.icon': 'Tákn',
    'adminSettings.iconUrl': 'Tákn vefslóð',
    'adminSettings.id': 'Auðkenni',
    'adminSettings.imageSize': 'Stærð myndar',
    'adminSettings.importData': 'Flytja inn gögn',
    'adminSettings.importSettings': 'Flytja inn stillingar',
    'adminSettings.incompleteSetup': 'Ólokið uppsetning',
    'adminSettings.initialShippingCost': 'Upphaflegur sendingarverð',
    'adminSettings.integration': 'Samþætting',
    'adminSettings.integrationActive': 'Samþætting virk',
    'adminSettings.integrationId': 'Samþættingar auðkenni',
    'adminSettings.integrationKey': 'Samþættingar lykill',
    'adminSettings.integrationName': 'Samþættingar nafn',
    'adminSettings.integrations': 'Samþættingar',
    'adminSettings.integrationsConfiguration': 'Samþættingar stillingar',
    'adminSettings.integrationsDescription': 'Samþættingar lýsing',
    'adminSettings.integrationsIntro': 'Samþættingar kynning',
    'adminSettings.integrationsKeyFeatures': 'Samþættingar lykileiginleikar',
    'adminSettings.integrationsNote': 'Samþættingar athugasemd',
    'adminSettings.integrationsRequired': 'Samþættingar nauðsynleg',
    'adminSettings.inventoryThreshold': 'Birgða þröskuldur',
    'adminSettings.ipAddress': 'IP tala',
    'adminSettings.ipRateLimit': 'IP taxtamörk',
    'adminSettings.ipWhiteList': 'IP hvítlistinn',
    'adminSettings.ipWhiteListDescription': 'IP hvítlistinn lýsing',
    'adminSettings.isActive': 'Virk',
    'adminSettings.isRecommendedPaymentProvider': 'Er aðfara greiðsluveitandi',
    'adminSettings.isRequired': 'Er krafist',
    'adminSettings.isRequired': 'Er krafist',
    'adminSettings.isSandbox': 'Er sandi',
    'adminSettings.isSelfManaged': 'Er sjálf stjórnað',
    'adminSettings.itineraryUrl': 'Itin vefslóð',
    'adminSettings.jetApiBaseUrl': 'Jet API grunn vefslóð',
    'adminSettings.jetApiKey': 'Jet API lykill',
    'adminSettings.jetApiSecret': 'Jet API leyndarmál',
    'adminSettings.jetIntegration': 'Jet samþætting',
    'adminSettings.jetMerchantId': 'Jet kaupmanns auðkenni',
    'adminSettings.jetRefreshToken': 'Jet endurnýja tákn',
    'adminSettings.jetSecret': 'Jet leyndarmál',
    'adminSettings.jetToken': 'Jet tákn',
    'adminSettings.jetTokenExpiry': 'Jet tákn rýrnun',
    'adminSettings.keywords': 'Leitarorð',
    'adminSettings.language': 'Tungumál',
    'adminSettings.languages': 'Tungumál',
    'adminSettings.largePhotoUrl': 'Stór mynd vefslóð',
    'adminSettings.lastName': 'Eftirnafn',
    'adminSettings.lastPaymentGateway': 'Síðasta greiðslumöttul',
    'adminSettings.lastRefreshTime': 'Síðasta endurnýjun tími',
    'adminSettings.lastRefresh': 'Síðasta endurnýjun',
    'adminSettings.lastSync': 'Síðasta samstilling',
    'adminSettings.lastUpdate': 'Síðasta uppfærsla',
    'adminSettings.lastUpdatedTime': 'Síðast uppfærð tíma',
    'adminSettings.lastUpdated': 'Síðast uppfært',
    'adminSettings.lastValidation': 'Síðasta staðfestingu',
    'adminSettings.lastVerified': 'Síðast staðfest',
    'adminSettings.latestOrderTime': 'Nýjasta pöntun tími',
    'adminSettings.latestOrders': 'Nýjustu pantanir',
    'adminSettings.layawayPayments': 'Greiðslur með láni',
    'adminSettings.layawayTerms': 'Lánaskilmálar',
    'adminSettings.legalCompanyName': 'Löglegt nafn fyrirtækis',
    'adminSettings.legalCompanyNameIs': 'Löglegt nafn fyrirtækis (Íslenska)',
    'adminSettings.license': 'Leyfi',
    'adminSettings.licensee': 'Leyfishan',
    'adminSettings.lightLogo': 'Lýs logo',
    'adminSettings.lightLogoUrl': 'Lýs logo vefslóð',
    'adminSettings.limitedTransactions': 'Takmörkuð viðskipti',
    'adminSettings.limits': 'Mörk',
    'adminSettings.locale': 'Staðsetning',
    'adminSettings.location': 'Staðsetning',
    'adminSettings.lockedUntil': 'Læst þar til',
    'adminSettings.logo': 'Logo',
    'adminSettings.logoAlignment': 'Logo innlíning',
    'adminSettings.logoUrl': 'Logo vefslóð',
    'adminSettings.logoutAfterMinutes': 'Útskrá eftir mínútur',
    'adminSettings.longDescription': 'Löng lýsing',
    'adminSettings.longDescriptionIs': 'Löng lýsing (Íslenska)',
    'adminSettings.lookupUrl': 'Fletta upp vefslóðar',
    'adminSettings.madWithLove': 'Gert með elsku',
    'adminSettings.magento': 'Magento',
    'adminSettings.magentoDescription': 'Magento lýsing',
    'adminSettings.magnetoUrl': 'Magneto vefslóð',
    'adminSettings.mailSettingsFailed': 'Tölvupóstur stillingar mistókst',
    'adminSettings.mailSettingsSuccess': 'Tölvupóstur stillingar árangur',
    'adminSettings.maintenanceMode': 'Viðhaldsstöð',
    'adminSettings.maintenanceModeActive': 'Viðhaldsstöð virk',
    'adminSettings.maintenanceModeDescription': 'Viðhaldsstöð lýsing',
    'adminSettings.managedByMerchant': 'Stjórnað af kaupmanninum',
    'adminSettings.managePaymentGateways': 'Stjórna greiðslumöttul',
    'adminSettings.manageProfile': 'Stjórna prófíl',
    'adminSettings.manageShippingOptions': 'Stjórna sendingarvalkostum',
    'adminSettings.mandatoryFields': 'Skyldulegir reitir',
    'adminSettings.manualIntegration': 'Handvirk samþætting',
    'adminSettings.manualShipping': 'Handvirk sending',
    'adminSettings.manualShippingDescription': 'Handvirk sendingarljóskindaslýsing',
    'adminSettings.manualTransfer': 'Handvirk flutningur',
    'adminSettings.marketCoverageAreas': 'Markaðsþekjusvæðis',
    'adminSettings.marketingConsent': 'Markaðssetningarsamtykki',
    'adminSettings.marketingDescription': 'Markaðssetning lýsing',
    'adminSettings.marketingPixel': 'Markaðssetning pixel',
    'adminSettings.marketingPreferences': 'Markaðssetning óskir',
    'adminSettings.markupAmount': 'Álagningarfjöldi',
    'adminSettings.masterPassword': 'Aðallykilorð',
    'adminSettings.matching': 'Samsvörun',
    'adminSettings.matchingDescription': 'Samsvörun lýsing',
    'adminSettings.materialDesign': 'Efnishönnun',
    'adminSettings.maxAttempts': 'Hámark tilraun',
    'adminSettings.maxDeliveryDays': 'Hámark sendingardag',
    'adminSettings.maxOrderAmount': 'Hámark pöntun magn',
    'adminSettings.maxOrderValue': 'Hámark pöntun gildi',
    'adminSettings.maxPrice': 'Hámarkverð',
    'adminSettings.maxTimeout': 'Hámark tímaútrás',
    'adminSettings.maxTries': 'Hámark tilraun',
    'adminSettings.maxUploadSize': 'Hámark hlaðu stærð',
    'adminSettings.maxUsers': 'Hámark notendur',
    'adminSettings.maximum': 'Hámark',
    'adminSettings.merchantApiKey': 'Kaupmannur API lykill',
    'adminSettings.merchantBaseUrl': 'Kaupmannur grunn vefslóð',
    'adminSettings.merchantCode': 'Kaupmannur kóði',
    'adminSettings.merchantId': 'Kaupmannur auðkenni',
    'adminSettings.merchantIdentification': 'Kaupmannur auðkenning',
    'adminSettings.merchantKey': 'Kaupmannur lykill',
    'adminSettings.merchantPassword': 'Kaupmannur lykilorð',
    'adminSettings.merchantSecret': 'Kaupmannur leyndarmál',
    'adminSettings.merchantSecretKey': 'Kaupmannur leyndarmál lykill',
    'adminSettings.merchantUsername': 'Kaupmannur notandanafn',
    'adminSettings.merchantUrl': 'Kaupmannur vefslóð',
    'adminSettings.meta': 'Meta',
    'adminSettings.metaDescription': 'Meta lýsing',
    'adminSettings.metaDescriptionIs': 'Meta lýsing (Íslenska)',
    'adminSettings.metaTitle': 'Meta titill',
    'adminSettings.metaTitleIs': 'Meta titill (Íslenska)',
    'adminSettings.metaUrl': 'Meta vefslóð',
    'adminSettings.method': 'Aðferð',
    'adminSettings.methodSettings': 'Aðferð stillingar',
    'adminSettings.methods': 'Aðferðir',
    'adminSettings.metric': 'Mælikvarði',
    'adminSettings.minAvailableQuantity': 'Min tiltækt magn',
    'adminSettings.minDeliveryDays': 'Lágmark sendingardag',
    'adminSettings.minOrderAmount': 'Lágmark pöntun magn',
    'adminSettings.minOrderValue': 'Lágmark pöntun gildi',
    'adminSettings.minPrice': 'Lágmarkverð',
    'adminSettings.minTimeout': 'Lágmark tímaútrás',
    'adminSettings.minimum': 'Lágmark',
    'adminSettings.minimumAge': 'Lágmark aldur',
    'adminSettings.minimumAgeForAlcohol': 'Lágmark aldur fyrir alkóhól',
    'adminSettings.minimumAgeForNicotine': 'Lágmark aldur fyrir nikotin',
    'adminSettings.minimumAgeVerification': 'Lágmark aldur staðfestingu',
    'adminSettings.minimumPurchaseAmount': 'Lágmark kaupar magn',
    'adminSettings.minimumPurchaseAmountDescription': 'Lágmark kaupar magn lýsing',
    'adminSettings.minimumQuantity': 'Lágmark magn',
    'adminSettings.minimumThreshold': 'Lágmark þröskuldur',
    'adminSettings.minioEndpoint': 'MinIO slut punkt',
    'adminSettings.minioKeyId': 'MinIO lykil auðkenni',
    'adminSettings.minioPolicyCorsUrl': 'MinIO stefna CORS vefslóð',
    'adminSettings.minioRegion': 'MinIO svæði',
    'adminSettings.minioSecret': 'MinIO leyndarmál',
    'adminSettings.minio': 'MinIO',
    'adminSettings.minioStorage': 'MinIO geymsla',
    'adminSettings.minioStorageDescription': 'MinIO geymsla lýsing',
    'adminSettings.minVersion': 'Min útgáfa',
    'adminSettings.mobileApp': 'Farsími app',
    'adminSettings.mobileAppActive': 'Farsími app virk',
    'adminSettings.mobileAppDescription': 'Farsími app lýsing',
    'adminSettings.mobileMenuStyle': 'Farsími valmynd stíll',
    'adminSettings.mobileNumber': 'Farsímans númer',
    'adminSettings.mobilePhoneNumber': 'Farsímans símanúmer',
    'adminSettings.mode': 'Hamur',
    'adminSettings.modelData': 'Módel gögn',
    'adminSettings.modelSettings': 'Módel stillingar',
    'adminSettings.modifyDescription': 'Breyta lýsingu',
    'adminSettings.modifyEmail': 'Breyta netfangi',
    'adminSettings.modifyExistingSettings': 'Breyta fyrirliggjandi stillingum',
    'adminSettings.modifyPaymentGateway': 'Breyta greiðslumöttul',
    'adminSettings.modifyProfile': 'Breyta prófíl',
    'adminSettings.modifyShippingOption': 'Breyta sendingarvalkosti',
    'adminSettings.moduleDescription': 'Einingar lýsing',
    'adminSettings.modules': 'Einingar',
    'adminSettings.modulesAllowedList': 'Einingar leyfðri listi',
    'adminSettings.modulesBlockedList': 'Einingar lokað listi',
    'adminSettings.modulesConfigured': 'Einingar stillt',
    'adminSettings.modulesEnabled': 'Einingar virkjuð',
    'adminSettings.modulesRequired': 'Einingar nauðsynlig',
    'adminSettings.mondayHours': 'Mánudags opnunartímar',
    'adminSettings.moneyInWords': 'Peningar í orðum',
    'adminSettings.monthlySchedule': 'Mánaðarleg áætlun',
    'adminSettings.monthlyScheduleDescription': 'Mánaðarleg áætlun lýsing',
    'adminSettings.more': 'Meira',
    'adminSettings.moreDetails': 'Fleiri smáatriði',
    'adminSettings.moreInformation': 'Fleiri upplýsingar',
    'adminSettings.moreOptions': 'Fleiri valkostir',
    'adminSettings.moreSettings': 'Fleiri stillingar',
    'adminSettings.mostRecentUpdate': 'Nýjasta uppfærsla',
    'adminSettings.multiChannel': 'Margrás',
    'adminSettings.multiChannelConfiguration': 'Margrás stillingar',
    'adminSettings.multiChannelDescription': 'Margrás lýsing',
    'adminSettings.multiChannelIntegration': 'Margrás samþætting',
    'adminSettings.multiCurrency': 'Margir gjaldmiðlar',
    'adminSettings.multiCurrencyConfiguration': 'Margir gjaldmiðlar stillingar',
    'adminSettings.multiCurrencyDescription': 'Margir gjaldmiðlar lýsing',
    'adminSettings.multiLanguage': 'Margt tungumál',
    'adminSettings.multiLanguageConfiguration': 'Margt tungumál stillingar',
    'adminSettings.multiLanguageDescription': 'Margt tungumál lýsing',
    'adminSettings.multipleShippingMethods': 'Margar sendingaraðferðir',
    'adminSettings.multipleShippingMethodsDescription': 'Margar sendingaraðferðir lýsing',
    'adminSettings.mustHavePaymentGateway': 'Verður að hafa greiðslumöttul',
    'adminSettings.mustHaveShippingOption': 'Verður að hafa sendingarvalkosti',
    'adminSettings.name': 'Nafn',
    'adminSettings.nameField': 'Nafn reit',
    'adminSettings.nameIs': 'Nafn (Íslenska)',
    'adminSettings.nameRequired': 'Nafn er krafist',
    'adminSettings.nameRequiredDescription': 'Nafn er krafist lýsing',
    'adminSettings.namingSuggestion': 'Nafn ábending',
    'adminSettings.namingSuggestionDescription': 'Nafn ábending lýsing',
    'adminSettings.national': 'Landsbundin',
    'adminSettings.nationalIdentifierNumber': 'Þjóðkennisfærslunúmer',
    'adminSettings.nationalIdentifierNumberIs': 'Þjóðkennisfærslunúmer (Íslenska)',
    'adminSettings.nationalIdentityNumber': 'Þjóðkennisfærslunúmer',
    'adminSettings.nationalIdNumber': 'Þjóðkennisfærslunúmer',
    'adminSettings.nationalIdNumberIs': 'Þjóðkennisfærslunúmer (Íslenska)',
    'adminSettings.nationalRegistration': 'Þjóðskrá',
    'adminSettings.nationalRegistrationNumber': 'Þjóðskrá númer',
    'adminSettings.nationalRegistrationNumberIs': 'Þjóðskrá númer (Íslenska)',
    'adminSettings.nationality': 'Þjóðerni',
    'adminSettings.nature': 'Eðli',
    'adminSettings.nearestWarehouse': 'Næsti vörugeymsla',
    'adminSettings.nearestWarehouseDescription': 'Næsti vörugeymsla lýsing',
    'adminSettings.needsApproval': 'Þarfnast samþykkis',
    'adminSettings.needsReview': 'Þarfnast endurskoðun',
    'adminSettings.negative': 'Neikvæð',
    'adminSettings.negativeBalance': 'Neikvæð jafnvægi',
    'adminSettings.negotiable': 'Samningsatriði',
    'adminSettings.neon': 'Neon',
    'adminSettings.neonDescription': 'Neon lýsing',
    'adminSettings.neopay': 'Neopay',
    'adminSettings.neopayDescription': 'Neopay lýsing',
    'adminSettings.neopayMerchantId': 'Neopay kaupmannur auðkenni',
    'adminSettings.neopayMerchantKey': 'Neopay kaupmannur lykill',
    'adminSettings.neopaySecret': 'Neopay leyndarmál',
    'adminSettings.neopayTestMode': 'Neopay prufu hamur',
    'adminSettings.neopayUrl': 'Neopay vefslóð',
    'adminSettings.nested': 'Hreiðrað',
    'adminSettings.nestedCategories': 'Hreiðruð flokkar',
    'adminSettings.nestingLevel': 'Hreiðran stig',
    'adminSettings.netAmount': 'Net magn',
    'adminSettings.netPayableAmount': 'Net greiðanlegt magn',
    'adminSettings.netSalesValue': 'Net söluvirði',
    'adminSettings.netVat': 'Net VSK',
    'adminSettings.network': 'Net',
    'adminSettings.networkConfiguration': 'Net stillingar',
    'adminSettings.networkDescription': 'Net lýsing',
    'adminSettings.networkSettings': 'Net stillingar',
    'adminSettings.newAddress': 'Nýtt heimilisfang',
    'adminSettings.newAddressForm': 'Nýtt heimilisfang form',
    'adminSettings.newArrival': 'Ný komu',
    'adminSettings.newArrivalDays': 'Ný komu dagar',
    'adminSettings.newArrivalDescription': 'Ný komu lýsing',
    'adminSettings.newArrivalDescription': 'Ný komu lýsing',
    'adminSettings.newArrivalHowMany': 'Ný komu hversu margir',
    'adminSettings.newArrivalHowManyDescription': 'Ný komu hversu margir lýsing',
    'adminSettings.newArrivalMarkingDays': 'Ný komu merking dagar',
    'adminSettings.newArrivalMarkingDaysDescription': 'Ný komu merking dagar lýsing',
    'adminSettings.newArrivalSettings': 'Ný komu stillingar',
    'adminSettings.newArrivalSettingsDescription': 'Ný komu stillingar lýsing',
    'adminSettings.newCategory': 'Nýr flokkur',
    'adminSettings.newCategoryForm': 'Nýr flokkur form',
    'adminSettings.newColor': 'Nýr litur',
    'adminSettings.newCountry': 'Nýtt land',
    'adminSettings.newCoupon': 'Nýr afsláttarmiði',
    'adminSettings.newCustomField': 'Nýr sérsniðinn reit',
    'adminSettings.newCustomIntegration': 'Ný sérstillt samþætting',
    'adminSettings.newCustomization': 'Ný sérstilling',
    'adminSettings.newCustomizationCategory': 'Ný sérstilling flokkur',
    'adminSettings.newCustomizationCategoryDescription': 'Ný sérstilling flokkur lýsing',
    'adminSettings.newDaysAdded': 'Nýir dagar bætir við',
    'adminSettings.newDeliveryZone': 'Ný sendingarsvæði',
    'adminSettings.newDomain': 'Nýtt lén',
    'adminSettings.newDomainSetup': 'Ný lénauppsetning',
    'adminSettings.newEarnings': 'Nýir tekjur',
    'adminSettings.newEndDate': 'Ný lokadagsetning',
    'adminSettings.newEntry': 'Ný færsla',
    'adminSettings.newEvent': 'Ný atburður',
    'adminSettings.newExpiredTime': 'Nýr rýrnun tími',
    'adminSettings.newFile': 'Ný skrá',
    'adminSettings.newFinance': 'Ný fjármál',
    'adminSettings.newFiscalYear': 'Nýtt fjárhagsár',
    'adminSettings.newFontSize': 'Nýr letursstærð',
    'adminSettings.newFontStyle': 'Nýr leturs stíll',
    'adminSettings.newForm': 'Nýtt form',
    'adminSettings.newFormField': 'Nýtt form reit',
    'adminSettings.newGiftCard': 'Nýr gjafakort',
    'adminSettings.newGiftCardCategory': 'Nýr gjafakort flokkur',
    'adminSettings.newGroup': 'Ný hópur',
    'adminSettings.newGroupDescription': 'Ný hópur lýsing',
    'adminSettings.newGroupName': 'Ný hópur nafn',
    'adminSettings.newGroupPermissions': 'Ný hópur heimildir',
    'adminSettings.newGroupRole': 'Ný hópur hlutverk',
    'adminSettings.newGroupSettings': 'Ný hópur stillingar',
    'adminSettings.newHeading': 'Nýr fyrirsögnin',
    'adminSettings.newHeight': 'Ný hæð',
    'adminSettings.newHistory': 'Ný saga',
    'adminSettings.newIcon': 'Nýr tákn',
    'adminSettings.newID': 'Nýtt auðkenni',
    'adminSettings.newImage': 'Ný mynd',
    'adminSettings.newImageSize': 'Ný mynd stærð',
    'adminSettings.newImageUrl': 'Ný mynd vefslóð',
    'adminSettings.newInformation': 'Nýar upplýsingar',
    'adminSettings.newIntegration': 'Ný samþætting',
    'adminSettings.newIntegrationMethod': 'Ný samþætting aðferð',
    'adminSettings.newIntegrationNote': 'Ný samþætting athugasemd',
    'adminSettings.newIntegrationSetup': 'Ný samþætting uppsetning',
    'adminSettings.newIntegrationSettings': 'Ný samþætting stillingar',
    'adminSettings.newIntegrationTitle': 'Ný samþætting titill',
    'adminSettings.newIssue': 'Nýtt mál',
    'adminSettings.newIssueCategory': 'Nýtt mál flokkur',
    'adminSettings.newIssueDescription': 'Nýtt mál lýsing',
    'adminSettings.newIssueForm': 'Nýtt mál form',
    'adminSettings.newIssueNote': 'Nýtt mál athugasemd',
    'adminSettings.newIssueStatus': 'Nýtt mál staða',
    'adminSettings.newIssueType': 'Nýtt mál tegund',
    'adminSettings.newJournal': 'Ný tímarit',
    'adminSettings.newJournalEntry': 'Ný tímarit færsla',
    'adminSettings.newKeyField': 'Nýr lykill reit',
    'adminSettings.newKeyValue': 'Nýr lykill gildi',
    'adminSettings.newLanguage': 'Nýtt tungumál',
    'adminSettings.newLanguageCode': 'Nýtt tungumál kóði',
    'adminSettings.newLanguageItem': 'Nýtt tungumál atriði',
    'adminSettings.newLayout': 'Ný útlit',
    'adminSettings.newLayoutName': 'Ný útlit nafn',
    'adminSettings.newLayoutSettings': 'Ný útlit stillingar',
    'adminSettings.newLength': 'Ný lengd',
    'adminSettings.newLimit': 'Ný mörk',
    'adminSettings.newLine': 'Ný lína',
    'adminSettings.newLineItem': 'Nýr línuatriðir',
    'adminSettings.newLineItemDescription': 'Nýr línuatriðir lýsing',
    'adminSettings.newLink': 'Nýr tengill',
    'adminSettings.newLinkName': 'Nýr tengill nafn',
    'adminSettings.newLinkText': 'Nýr tengill texta',
    'adminSettings.newLinkTitle': 'Nýr tengill titill',
    'adminSettings.newLinkUrl': 'Nýr tengill vefslóð',
    'adminSettings.newList': 'Nýr listi',
    'adminSettings.newListDescription': 'Nýr listi lýsing',
    'adminSettings.newListItem': 'Nýr listi atriði',
    'adminSettings.newListName': 'Nýr listi nafn',
    'adminSettings.newListSettings': 'Nýr listi stillingar',
    'adminSettings.newListType': 'Nýr listi tegund',
    'adminSettings.newLocation': 'Ný staðsetning',
    'adminSettings.newLocationName': 'Ný staðsetning nafn',
    'adminSettings.newLocationSettings': 'Ný staðsetning stillingar',
    'adminSettings.newLog': 'Nýr atvikaskrá',
    'adminSettings.newLogEntry': 'Nýr atvikaskrá færsla',
    'adminSettings.newLogFile': 'Nýr atvikaskrá skrá',
    'adminSettings.newLogLevel': 'Nýr atvikaskrá stig',
    'adminSettings.newLogName': 'Nýr atvikaskrá nafn',
    'adminSettings.newLogType': 'Nýr atvikaskrá tegund',
    'adminSettings.newLogoAlignment': 'Ný logo innlíning',
    'adminSettings.newLogoDescription': 'Ný logo lýsing',
    'adminSettings.newLogoSize': 'Ný logo stærð',
    'adminSettings.newLogoStyle': 'Ný logo stíll',
    'adminSettings.newLowStockWarning': 'Ný lág birgða viðvörun',
    'adminSettings.newLowStockWarningDescription': 'Ný lág birgða viðvörun lýsing',
    'adminSettings.newLowStockWarningLevel': 'Ný lág birgða viðvörun stig',
    'adminSettings.newMaintenance': 'Ný viðhald',
    'adminSettings.newMaintenanceDescription': 'Ný viðhald lýsing',
    'adminSettings.newMaintenanceEndTime': 'Ný viðhald endanleg tími',
    'adminSettings.newMaintenanceMessage': 'Ný viðhald skilaboð',
    'adminSettings.newMaintenanceStartTime': 'Ný viðhald upphaf tími',
    'adminSettings.newMaintenanceStatus': 'Ný viðhald staða',
    'adminSettings.newMaintenanceWindow': 'Ný viðhald gluggi',
    'adminSettings.newManufacturer': 'Nýr framleiðandi',
    'adminSettings.newManufacturerDescription': 'Nýr framleiðandi lýsing',
    'adminSettings.newManufacturerInfo': 'Nýr framleiðandi upplýsingar',
    'adminSettings.newManufacturerName': 'Nýr framleiðandi nafn',
    'adminSettings.newManufacturerSettings': 'Nýr framleiðandi stillingar',
    'adminSettings.newMargin': 'Ný framlegð',
    'adminSettings.newMarketplace': 'Ný markaður',
    'adminSettings.newMarketplaceDescription': 'Ný markaður lýsing',
    'adminSettings.newMarketplaceIntegration': 'Ný markaður samþætting',
    'adminSettings.newMarketplaceSettings': 'Ný markaður stillingar',
    'adminSettings.newMarketplaceUrl': 'Ný markaður vefslóð',
    'adminSettings.newMarkup': 'Ný álagning',
    'adminSettings.newMarkupAmount': 'Ný álagning magn',
    'adminSettings.newMarkupDescription': 'Ný álagning lýsing',
    'adminSettings.newMarkupPercentage': 'Ný álagning prósenta',
    'adminSettings.newMarkupReason': 'Ný álagning ástæða',
    'adminSettings.newMarkupSettings': 'Ný álagning stillingar',
    'adminSettings.newMask': 'Ný gríma',
    'adminSettings.newMaskDescription': 'Ný gríma lýsing',
    'adminSettings.newMaskPattern': 'Ný gríma mynstur',
    'adminSettings.newMaskSettings': 'Ný gríma stillingar',
    'adminSettings.newMaterial': 'Nýr efni',
    'adminSettings.newMaterialCategory': 'Nýr efni flokkur',
    'adminSettings.newMaterialDescription': 'Nýr efni lýsing',
    'adminSettings.newMaterialSettings': 'Nýr efni stillingar',
    'adminSettings.newMaterialSpecifications': 'Nýr efni forskrift',
    'adminSettings.newMeasurement': 'Ný mæling',
    'adminSettings.newMeasurementDescription': 'Ný mæling lýsing',
    'adminSettings.newMeasurementForm': 'Ný mæling form',
    'adminSettings.newMeasurementType': 'Ný mæling tegund',
    'adminSettings.newMeasurementUnit': 'Ný mæling eining',
    'adminSettings.newMediaItem': 'Nýr miðli atriði',
    'adminSettings.newMediaLibrary': 'Ný miðli bóksafn',
    'adminSettings.newMediaType': 'Nýr miðli tegund',
    'adminSettings.newMediatorMessage': 'Nýr millist skilaboð',
    'adminSettings.newMediatorProfile': 'Nýr millist prófíl',
    'adminSettings.newMediatorService': 'Nýr millist þjónusta',
    'adminSettings.newMediatorServiceDescription': 'Nýr millist þjónusta lýsing',
    'adminSettings.newMediatorSettings': 'Nýr millist stillingar',
    'adminSettings.newMember': 'Nýr meðlimur',
    'adminSettings.newMemberDescription': 'Nýr meðlimur lýsing',
    'adminSettings.newMemberForm': 'Nýr meðlimur form',
    'adminSettings.newMemberRole': 'Nýr meðlimur hlutverk',
    'adminSettings.newMemberSettings': 'Nýr meðlimur stillingar',
    'adminSettings.newMemory': 'Ný minni',
    'adminSettings.newMemorySize': 'Ný minni stærð',
    'adminSettings.newMemoryType': 'Ný minni tegund',
    'adminSettings.newMemoryUsage': 'Ný minni notkun',
    'adminSettings.newMerchant': 'Nýr kaupmaður',
    'adminSettings.newMerchantAccount': 'Nýr kaupmaður reikningur',
    'adminSettings.newMerchantAgreement': 'Nýr kaupmaður samningur',
    'adminSettings.newMerchantBusinessDetails': 'Nýr kaupmaður viðskipti smáatriði',
    'adminSettings.newMerchantBankDetails': 'Nýr kaupmaður banki smáatriði',
    'adminSettings.newMerchantCommission': 'Nýr kaupmaður þóknun',
    'adminSettings.newMerchantCommissionPercentage': 'Nýr kaupmaður þóknun prósenta',
    'adminSettings.newMerchantCommissionStructure': 'Nýr kaupmaður þóknun uppbygging',
    'adminSettings.newMerchantCompanyName': 'Nýr kaupmaður fyrirtæki nafn',
    'adminSettings.newMerchantContactDetails': 'Nýr kaupmaður samband smáatriði',
    'adminSettings.newMerchantDescription': 'Nýr kaupmaður lýsing',
    'adminSettings.newMerchantDocumentation': 'Nýr kaupmaður skjöl',
    'adminSettings.newMerchantForm': 'Nýr kaupmaður form',
    'adminSettings.newMerchantId': 'Nýr kaupmaður auðkenni',
    'adminSettings.newMerchantInfo': 'Nýr kaupmaður upplýsingar',
    'adminSettings.newMerchantInformation': 'Nýr kaupmaður upplýsingar',
    'adminSettings.newMerchantInvoicing': 'Nýr kaupmaður reikningsútfærsla',
    'adminSettings.newMerchantKyc': 'Nýr kaupmaður KYC',
    'adminSettings.newMerchantLevel': 'Nýr kaupmaður stig',
    'adminSettings.newMerchantLogo': 'Nýr kaupmaður logo',
    'adminSettings.newMerchantName': 'Nýr kaupmaður nafn',
    'adminSettings.newMerchantNote': 'Nýr kaupmaður athugasemd',
    'adminSettings.newMerchantOnboarding': 'Nýr kaupmaður sannmörkun',
    'adminSettings.newMerchantPaymentGateway': 'Nýr kaupmaður greiðslu gátt',
    'adminSettings.newMerchantPaymentMethods': 'Nýr kaupmaður greiðslu aðferðir',
    'adminSettings.newMerchantPaymentSettings': 'Nýr kaupmaður greiðslu stillingar',
    'adminSettings.newMerchantPayoutSchedule': 'Nýr kaupmaður útborgun áætlun',
    'adminSettings.newMerchantPerformance': 'Nýr kaupmaður framkvæmd',
    'adminSettings.newMerchantPerformanceMetrics': 'Nýr kaupmaður framkvæmd mælikvarðar',
    'adminSettings.newMerchantPermissions': 'Nýr kaupmaður heimildir',
    'adminSettings.newMerchantPolicies': 'Nýr kaupmaður stefnur',
    'adminSettings.newMerchantProfile': 'Nýr kaupmaður prófíl',
    'adminSettings.newMerchantProfileSettings': 'Nýr kaupmaður prófíl stillingar',
    'adminSettings.newMerchantProducts': 'Nýr kaupmaður vörur',
    'adminSettings.newMerchantQualification': 'Nýr kaupmaður hæfing',
    'adminSettings.newMerchantRegistration': 'Nýr kaupmaður skráning',
    'adminSettings.newMerchantRole': 'Nýr kaupmaður hlutverk',
    'adminSettings.newMerchantSales': 'Nýr kaupmaður sala',
    'adminSettings.newMerchantServiceAgreement': 'Nýr kaupmaður þjónusta samningur',
    'adminSettings.newMerchantSetting': 'Nýr kaupmaður stillingu',
    'adminSettings.newMerchantSettings': 'Nýr kaupmaður stillingar',
    'adminSettings.newMerchantShippingZones': 'Nýr kaupmaður sending svæðis',
    'adminSettings.newMerchantStatus': 'Nýr kaupmaður staða',
    'adminSettings.newMerchantStores': 'Nýr kaupmaður verslanir',
    'adminSettings.newMerchantTaxConfiguration': 'Nýr kaupmaður skattar stillingar',
    'adminSettings.newMerchantTermsAndConditions': 'Nýr kaupmaður skilmálar og skilyrði',
    'adminSettings.newMerchantTermsConditions': 'Nýr kaupmaður skilmálar skilyrði',
    'adminSettings.newMerchantTestMode': 'Nýr kaupmaður prófun hamur',
    'adminSettings.newMerchantTier': 'Nýr kaupmaður lag',
    'adminSettings.newMerchantType': 'Nýr kaupmaður tegund',
    'adminSettings.newMerchantTypeOfEntity': 'Nýr kaupmaður tegund eining',
    'adminSettings.newMerchantUser': 'Nýr kaupmaður notandi',
    'adminSettings.newMerchantVerification': 'Nýr kaupmaður staðfestingu',
    'adminSettings.newMerchantVerificationStatus': 'Nýr kaupmaður staðfestingu staða',
    'adminSettings.newMerchantWarning': 'Nýr kaupmaður viðvörun',
    'adminSettings.newMessage': 'Ný skilaboð',
    'adminSettings.newMessageCategory': 'Ný skilaboð flokkur',
    'adminSettings.newMessageContent': 'Ný skilaboð efni',
    'adminSettings.newMessageDescription': 'Ný skilaboð lýsing',
    'adminSettings.newMessageForm': 'Ný skilaboð form',
    'adminSettings.newMessagePlaceholder': 'Ný skilaboð staðhaldari',
    'adminSettings.newMessageStatus': 'Ný skilaboð staða',
    'adminSettings.newMessageTemplate': 'Ný skilaboð sniðmát',
    'adminSettings.newMessageTemplateDescription': 'Ný skilaboð sniðmát lýsing',
    'adminSettings.newMessageType': 'Ný skilaboð tegund',
    'adminSettings.newMessenger': 'Nýr herðir',
    'adminSettings.newMetal': 'Nýr málmur',
    'adminSettings.newMetalDescription': 'Nýr málmur lýsing',
    'adminSettings.newMetalPurity': 'Nýr málmur hreinni',
    'adminSettings.newMetalType': 'Nýr málmur tegund',
    'adminSettings.newMeterReading': 'Ný mæli les',
    'adminSettings.newMeterReadingDescription': 'Ný mæli les lýsing',
    'adminSettings.newMeterReadingForm': 'Ný mæli les form',
    'adminSettings.newMeterReadingType': 'Ný mæli les tegund',
    'adminSettings.newMeterType': 'Nýr mæli tegund',
    'adminSettings.newMethodology': 'Ný aðferðafræði',
    'adminSettings.newMethodologyDescription': 'Ný aðferðafræði lýsing',
    'adminSettings.newMethodologyName': 'Ný aðferðafræði nafn',
    'adminSettings.newMethodologySettings': 'Ný aðferðafræði stillingar',
    'adminSettings.newMethodologySteps': 'Ný aðferðafræði skref',
    'adminSettings.newMetric': 'Ný mælikvarði',
    'adminSettings.newMetricCategory': 'Ný mælikvarði flokkur',
    'adminSettings.newMetricDescription': 'Ný mælikvarði lýsing',
    'adminSettings.newMetricFormula': 'Ný mælikvarði formúla',
    'adminSettings.newMetricName': 'Ný mælikvarði nafn',
    'adminSettings.newMetricSettings': 'Ný mælikvarði stillingar',
    'adminSettings.newMetricType': 'Ný mælikvarði tegund',
    'adminSettings.newMetricUnit': 'Ný mælikvarði eining',
    'adminSettings.newMetrics': 'Nýir mælikvarðar',
    'adminSettings.newMetricsCollection': 'Ný mælikvarði söfnun',
    'adminSettings.newMetricsDescription': 'Nýir mælikvarðar lýsing',
    'adminSettings.newMetricsDisplay': 'Nýir mælikvarðar birta',
    'adminSettings.newMetricsSettings': 'Nýir mælikvarðar stillingar',
    'adminSettings.newMetrics': 'Nýir mælikvarðar',
}

def main():
    print("="*70)
    print("FINAL COMPREHENSIVE ICELANDIC TRANSLATION")
    print("="*70)

    print(f"\nLoading {len(COMPREHENSIVE_TRANSLATIONS)} comprehensive translations...")
    print(f"Processing 30 batches...\n")

    total_keys = 0
    translated_count = 0
    completed = 0

    for i in range(1, 31):
        batch_file = BATCH_DIR / f'batch-{str(i).zfill(3)}.json'
        output_file = BATCH_DIR / f'batch-{str(i).zfill(3)}-translated.json'

        if not batch_file.exists():
            continue

        try:
            with open(batch_file, 'r', encoding='utf-8') as f:
                batch = json.load(f)

            keys = batch.get('keys', [])
            result = {}

            for key in keys:
                if key in COMPREHENSIVE_TRANSLATIONS:
                    result[key] = COMPREHENSIVE_TRANSLATIONS[key]
                    translated_count += 1
                else:
                    result[key] = key

            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(result, f, ensure_ascii=False, indent=2)

            total_keys += len(keys)
            completed += 1
            trans_count = sum(1 for k in keys if k in COMPREHENSIVE_TRANSLATIONS)
            print(f"Batch {str(i).zfill(3)}: {len(keys)} keys ({trans_count} translated)")

        except Exception as e:
            print(f"Error processing batch {str(i).zfill(3)}: {str(e)}")

    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Batches processed: {completed}/30")
    print(f"Total keys: {total_keys}")
    print(f"Translated with dictionary: {translated_count}")
    print(f"Remaining (fallback to key): {total_keys - translated_count}")
    print(f"Translation coverage: {(translated_count/total_keys*100):.1f}%")
    print(f"{'='*70}")
    print(f"\nAll batch files have been updated!")
    print(f"Output location: {BATCH_DIR}")

if __name__ == '__main__':
    main()
